const constants = {
  ARTICLE_TITLE_MINLENGTH: 3,
  ARTICLE_TITLE_MAXLENGTH: 50,
  SKILL_TITLE_MINLENGTH: 3,
  SKILL_TITLE_MAXLENGTH: 15,
  ADMIN_USERNAME: 'romas',
  ADMIN_PASSWORD: '12345',
};

module.exports = constants;
